stages:
    - build

newsletter:
    image: python:latest
    stage: build
    before_script:
        - python -m venv env
        - env/Scripts/activate
        - pip install -r newsletter/app/requirements.txt
    script:
        -python  newsletter/app/main.py
